export const CATEGORIES = [
  { id: 1, name: "Авто, мото", multiplier: 2.3 },
  { id: 2, name: "Автомобильная электроника", multiplier: 2.2 },
  { id: 3, name: "Автосервис", multiplier: 2.0 },
  { id: 4, name: "Автострахование", multiplier: 2.4 },
  { id: 5, name: "Агентства недвижимости", multiplier: 2.8 },
  { id: 6, name: "Аксессуары", multiplier: 1.5 },
  { id: 7, name: "Активный отдых", multiplier: 1.8 },
  { id: 8, name: "Антиквариат", multiplier: 1.9 },
  { id: 9, name: "Аптека", multiplier: 2.6 },
  { id: 10, name: "Аренда авто", multiplier: 2.1 },
  { id: 11, name: "Аренда недвижимости", multiplier: 2.5 },
  { id: 12, name: "Аудио и видеотехника", multiplier: 2.0 },
  { id: 13, name: "Аудит и консалтинг", multiplier: 2.4 },
  { id: 14, name: "Бани и сауны", multiplier: 1.6 },
  { id: 15, name: "Банковские услуги", multiplier: 2.7 },
  { id: 16, name: "Банковское оборудование", multiplier: 2.2 },
  { id: 17, name: "Бизнес", multiplier: 2.3 },
  { id: 18, name: "Бухучёт и налоги", multiplier: 2.3 },
  { id: 19, name: "Бытовой ремонт", multiplier: 1.7 },
  { id: 20, name: "Бытовые услуги", multiplier: 1.6 },
  { id: 21, name: "Вакансии", multiplier: 2.0 },
  { id: 22, name: "Велосипеды", multiplier: 1.6 },
  { id: 23, name: "Ветеринарные клиники", multiplier: 1.9 },
  { id: 24, name: "Видеоигры", multiplier: 1.8 },
  { id: 25, name: "Вклады и депозиты", multiplier: 2.5 },
  { id: 26, name: "Водный спорт", multiplier: 1.5 },
  { id: 27, name: "Всё для офиса", multiplier: 1.9 },
  { id: 28, name: "Высшее образование", multiplier: 2.6 },
  { id: 29, name: "ГСМ(горючее) и автохимия", multiplier: 1.9 },
  { id: 30, name: "Грузовые авто и автобусы", multiplier: 2.1 },
  { id: 31, name: "Грузоперевозки", multiplier: 2.0 },
  { id: 32, name: "Дача и сад", multiplier: 1.6 },
  { id: 33, name: "Двери и окна", multiplier: 1.8 },
  { id: 34, name: "Декоративная косметика", multiplier: 1.7 },
  { id: 35, name: "Детская мебель", multiplier: 1.7 },
  { id: 36, name: "Детская обувь", multiplier: 1.6 },
  { id: 37, name: "Детская одежда", multiplier: 1.6 },
  { id: 38, name: "Детские товары и услуги", multiplier: 1.7 },
  { id: 39, name: "Детский лагерь", multiplier: 1.8 },
  { id: 40, name: "Детское питание", multiplier: 1.9 },
  { id: 41, name: "Диетические программы", multiplier: 2.0 },
  { id: 42, name: "Дизайн-студии", multiplier: 1.9 },
  { id: 43, name: "Дом, ремонт", multiplier: 1.9 },
  { id: 44, name: "Домашние животные", multiplier: 1.6 },
  { id: 45, name: "Доставка еды", multiplier: 1.8 },
  { id: 46, name: "Дошкольное образование", multiplier: 1.9 },
  { id: 47, name: "Другое", multiplier: 1.3 },
  { id: 48, name: "Животные", multiplier: 1.4 },
  { id: 49, name: "Жилая недвижимость", multiplier: 2.7 },
  { id: 50, name: "Загородная недвижимость", multiplier: 2.6 },
  { id: 51, name: "Запчасти", multiplier: 1.9 },
  { id: 52, name: "Зимние виды спорта", multiplier: 1.5 },
  { id: 53, name: "Знакомства", multiplier: 1.4 },
  { id: 54, name: "Зоомагазины", multiplier: 1.5 },
  { id: 55, name: "Игровые приставки", multiplier: 1.7 },
  { id: 56, name: "Игры и игрушки", multiplier: 1.5 },
  { id: 57, name: "Изготовление и размещение рекламы", multiplier: 2.2 },
  { id: 58, name: "Издательство и полиграфия", multiplier: 1.8 },
  { id: 59, name: "Инвестиционные компании", multiplier: 2.8 },
  { id: 60, name: "Инструменты и оборузование", multiplier: 1.9 },
  { id: 61, name: "Интернет-СМИ", multiplier: 1.7 },
  { id: 62, name: "Интернет-обучение", multiplier: 2.6 },
  { id: 63, name: "Интернет-провайдер", multiplier: 2.1 },
  { id: 64, name: "Информационные порталы и отзывы", multiplier: 1.6 },
  { id: 65, name: "Канцтовары и расходные материалы", multiplier: 1.3 },
  { id: 66, name: "Карты памяти и накопители", multiplier: 1.8 },
  { id: 67, name: "Кафе, бары, рестораны", multiplier: 1.9 },
  { id: 68, name: "Квесты", multiplier: 1.4 },
  { id: 69, name: "Кино", multiplier: 1.5 },
  { id: 70, name: "Клининговые услуги", multiplier: 1.6 },
  { id: 71, name: "Книги и печатные издания", multiplier: 1.4 },
  { id: 72, name: "Коляски", multiplier: 1.5 },
  { id: 73, name: "Коммерческая недвижимость", multiplier: 2.6 },
  { id: 74, name: "Компьютеры и ноутбуки", multiplier: 2.5 },
  { id: 75, name: "Концерты, мероприятия", multiplier: 1.7 },
  { id: 76, name: "Косметология и пластическая хирургия", multiplier: 2.4 },
  { id: 77, name: "Красота, здоровье", multiplier: 2.1 },
  { id: 78, name: "Кредитование физлиц", multiplier: 2.4 },
  { id: 79, name: "Кредитование юрлиц", multiplier: 2.5 },
  { id: 80, name: "Крупная техника для кухни", multiplier: 1.8 },
  { id: 81, name: "Кулинарные рецепты", multiplier: 1.3 },
  { id: 82, name: "Курьерские службы", multiplier: 1.9 },
  { id: 83, name: "Легковые автомобили", multiplier: 2.3 },
  { id: 84, name: "Летние виды спорта", multiplier: 1.4 },
  { id: 85, name: "Логистика", multiplier: 2.0 },
  { id: 86, name: "Ломбарды", multiplier: 1.9 },
  { id: 87, name: "Магазин подарков", multiplier: 1.4 },
  { id: 88, name: "Маркетинговые услуги", multiplier: 2.2 },
  { id: 89, name: "Мебель и предметы интерьера", multiplier: 1.8 },
  { id: 90, name: "Медицина", multiplier: 2.8 },
  { id: 91, name: "Мед услуги", multiplier: 2.6 },
  { id: 92, name: "Мелкая техника для кухни", multiplier: 1.5 },
  { id: 93, name: "Мобильные телефоны", multiplier: 2.5 },
  { id: 94, name: "Мотоциклы и мототехника", multiplier: 1.9 },
  { id: 95, name: "Мужская и женская одежда", multiplier: 1.6 },
  { id: 96, name: "Музеи, выставки", multiplier: 1.3 },
  { id: 97, name: "Музыка", multiplier: 1.4 },
  { id: 98, name: "Наркологические клиники", multiplier: 2.1 },
  { id: 99, name: "Настольные игры", multiplier: 1.4 },
  { id: 100, name: "Недвижимость", multiplier: 2.7 },
  { id: 101, name: "Нижнее бельё", multiplier: 1.4 },
  { id: 102, name: "Ночные клубы", multiplier: 1.5 },
  { id: 103, name: "Образование и работа", multiplier: 2.2 },
  { id: 104, name: "Обувь", multiplier: 1.5 },
  { id: 105, name: "Обучающие курсы", multiplier: 2.4 },
  { id: 106, name: "Общественные организации", multiplier: 1.3 },
  { id: 107, name: "Объявления", multiplier: 1.2 },
  { id: 108, name: "Одежда и обувь", multiplier: 1.5 },
  { id: 109, name: "Онлайн-игры", multiplier: 1.7 },
  { id: 110, name: "Оператор сотовой связи", multiplier: 2.3 },
  { id: 111, name: "Оператор стационарной связи", multiplier: 2.1 },
  { id: 112, name: "Оптика", multiplier: 1.9 },
  { id: 113, name: "Организации культуры", multiplier: 1.3 },
  { id: 114, name: "Отели, хостелы", multiplier: 1.9 },
  { id: 115, name: "Офисная мебель", multiplier: 1.9 },
  { id: 116, name: "Офисная техника", multiplier: 2.0 },
  { id: 117, name: "Оформление виз и паспортов", multiplier: 2.2 },
  { id: 118, name: "Охота и рыбалка", multiplier: 1.3 },
  { id: 119, name: "Охрана и сигнализация", multiplier: 1.9 },
  { id: 120, name: "Парки отдыха, зоопарки", multiplier: 1.3 },
  { id: 121, name: "Парники и теплицы", multiplier: 1.4 },
  { id: 122, name: "Парфюмерия", multiplier: 1.6 },
  { id: 123, name: "Парфюмерийные устройства", multiplier: 1.5 },
  { id: 124, name: "Печатные издания", multiplier: 1.3 },
  { id: 125, name: "Пиротехника", multiplier: 1.2 },
  { id: 126, name: "Платёжные системы, пластиковые карты", multiplier: 2.8 },
  { id: 127, name: "Подарки и сувениры", multiplier: 1.3 },
  { id: 128, name: "Поздравление", multiplier: 1.2 },
  { id: 129, name: "Портативная техника", multiplier: 1.9 },
  { id: 130, name: "Посуда и кухня", multiplier: 1.4 },
  { id: 131, name: "Почтовые услуги", multiplier: 1.6 },
  { id: 132, name: "Пошив и ремонт одежды", multiplier: 1.5 },
  { id: 133, name: "Программное обеспечение", multiplier: 2.9 },
  { id: 134, name: "Продукты", multiplier: 1.4 },
  { id: 135, name: "Продукты питания", multiplier: 1.5 },
  { id: 136, name: "Производственные услуги", multiplier: 2.0 },
  { id: 137, name: "Промышленное оборудование", multiplier: 2.1 },
  { id: 138, name: "Промышленный транспорт", multiplier: 2.0 },
  { id: 139, name: "Противоугонные средства", multiplier: 1.8 },
  { id: 140, name: "Психология", multiplier: 1.6 },
  { id: 141, name: "Радиостанции", multiplier: 1.5 },
  { id: 142, name: "Развлекательное сообщество", multiplier: 1.2 },
  { id: 143, name: "Развлекательные центры", multiplier: 1.4 },
  { id: 144, name: "Развлечения и хобби", multiplier: 1.3 },
  { id: 145, name: "Разработка веб-сайтов", multiplier: 2.7 },
  { id: 146, name: "Растения, семена, рассада", multiplier: 1.4 },
  { id: 147, name: "Ремонт помещений", multiplier: 1.9 },
  { id: 148, name: "Садовая мебель и декор", multiplier: 1.4 },
  { id: 149, name: "Садовая техника", multiplier: 1.5 },
  { id: 150, name: "Садовый инвентарь", multiplier: 1.4 },
  { id: 151, name: "Салоны красоты", multiplier: 2.0 },
  { id: 152, name: "Салоны сотовой связи", multiplier: 2.1 },
  { id: 153, name: "Санаторно-оздоровительные центры", multiplier: 1.8 },
  { id: 154, name: "Сантехника и водоснабжение", multiplier: 1.8 },
  { id: 155, name: "Свадебные салоны", multiplier: 1.6 },
  { id: 156, name: "Секции и кружки", multiplier: 1.3 },
  { id: 157, name: "Социальные и общественные организации", multiplier: 1.3 },
  { id: 158, name: "Спорт и отдых", multiplier: 1.6 },
  { id: 159, name: "Спортивная одежда и обувь", multiplier: 1.6 },
  { id: 160, name: "Спортивное питание", multiplier: 2.0 },
  { id: 161, name: "Спортивные клубы и мероприятия", multiplier: 1.9 },
  { id: 162, name: "Спортивные товары", multiplier: 1.7 },
  { id: 163, name: "Спутниковый оператор связи", multiplier: 2.2 },
  { id: 164, name: "Среднее и доп", multiplier: 1.5 },
  { id: 165, name: "Средства борьбы с насекомыми", multiplier: 1.4 },
  { id: 166, name: "Стоматология", multiplier: 2.5 },
  { id: 167, name: "Страховые услуги для физлиц", multiplier: 2.4 },
  { id: 168, name: "Страховые услуги для юрлиц", multiplier: 2.5 },
  { id: 169, name: "Строительные конструкции", multiplier: 2.0 },
  { id: 170, name: "Строительство", multiplier: 2.2 },
  { id: 171, name: "Сувениры", multiplier: 1.3 },
  { id: 172, name: "Сумки и чемоданы", multiplier: 1.5 },
  { id: 173, name: "Супермаркет, рынок", multiplier: 1.5 },
  { id: 174, name: "Сценическое и аудиооборудование", multiplier: 1.8 },
  { id: 175, name: "Такси", multiplier: 1.8 },
  { id: 176, name: "Таможенные услуги", multiplier: 1.9 },
  { id: 177, name: "Театры, спектакли", multiplier: 1.3 },
  { id: 178, name: "Текстиль", multiplier: 1.4 },
  { id: 179, name: "Телевидение", multiplier: 1.6 },
  { id: 180, name: "Телекоммуникационное оборудование", multiplier: 2.0 },
  { id: 181, name: "Техника для дома", multiplier: 1.7 },
  { id: 182, name: "Техника для красоты", multiplier: 1.8 },
  { id: 183, name: "Техника и электроника", multiplier: 2.1 },
  { id: 184, name: "Технологическое оборудование", multiplier: 2.0 },
  { id: 185, name: "Товары для мам и малышей", multiplier: 1.7 },
  { id: 186, name: "Товары для праздников", multiplier: 1.3 },
  { id: 187, name: "Товары для рукоделия", multiplier: 1.3 },
  { id: 188, name: "Торговое оборудование", multiplier: 1.9 },
  { id: 189, name: "Торговые центры", multiplier: 1.8 },
  { id: 190, name: "Транспортные и почтовые услуги", multiplier: 1.8 },
  { id: 191, name: "Тренинги, семинары, лекции", multiplier: 2.2 },
  { id: 192, name: "Туризм и путешествия", multiplier: 2.1 },
  { id: 193, name: "Туры и турагентства", multiplier: 2.0 },
  { id: 194, name: "Услуги для автовладельцев", multiplier: 1.9 },
  { id: 195, name: "Услуги для владельцев животных", multiplier: 1.5 },
  { id: 196, name: "Услуги по организации праздников", multiplier: 1.4 },
  { id: 197, name: "Услуги проката", multiplier: 1.6 },
  { id: 198, name: "Услуги связи и интернет", multiplier: 2.1 },
  { id: 199, name: "Услуги фотографов, ведущих", multiplier: 1.5 },
  { id: 200, name: "Уход за волосами", multiplier: 1.7 },
  { id: 201, name: "Уход за телом и лицом", multiplier: 1.9 },
  { id: 202, name: "Учебная и профессиональная литература", multiplier: 1.5 },
  { id: 203, name: "Учеба за рубежом", multiplier: 2.6 },
  { id: 204, name: "Финансовые рынки", multiplier: 2.9 },
  { id: 205, name: "Финансы и страхование", multiplier: 2.9 },
  { id: 206, name: "Фитнес-центр", multiplier: 1.9 },
  { id: 207, name: "Фотографии, живопись", multiplier: 1.3 },
  { id: 208, name: "Химчистка и прачечная", multiplier: 1.4 },
  { id: 209, name: "Хозяйственные товары", multiplier: 1.4 },
  { id: 210, name: "Хостинг, сервера, домены", multiplier: 2.6 },
  { id: 211, name: "Цветы и растения", multiplier: 1.4 },
  { id: 212, name: "Чистящая и моющая техника", multiplier: 1.5 },
  { id: 213, name: "Шины и диски", multiplier: 1.9 },
  { id: 214, name: "Экскурсии", multiplier: 1.5 },
  { id: 215, name: "Электронные книги", multiplier: 1.3 },
  { id: 216, name: "Ювелирные изделия", multiplier: 2.2 },
  { id: 217, name: "Юридические услуги", multiplier: 2.7 },
];

export const PLATFORMS = [
  { id: 1, name: "Telegram", multiplier: 0.8 },
  { id: 2, name: "Instagram", multiplier: 1.2 },
  { id: 3, name: "YouTube", multiplier: 1.5 },
  { id: 4, name: "Сайт", multiplier: 1.0 },
];

export const POSTS_COUNT = [
  { id: 1, count: 4, name: "4 поста" },
  { id: 2, count: 7, name: "7 постов" },
  { id: 3, count: 14, name: "14 постов" },
  { id: 4, count: 21, name: "21 пост" },
  { id: 5, count: 30, name: "30 постов" },
];

export const FORMATS = [
  // Telegram (platformId: 1)
  { id: 1, platformId: 1, name: "Пост", multiplier: 1.0 },
  { id: 2, platformId: 1, name: "Закреп", multiplier: 1.5 },
  { id: 3, platformId: 1, name: "История", multiplier: 0.7 },
  { id: 4, platformId: 1, name: "Прямая ссылка", multiplier: 0.5 },

  // Instagram (platformId: 2)
  { id: 5, platformId: 2, name: "История", multiplier: 0.8 },
  { id: 6, platformId: 2, name: "Рилс", multiplier: 1.3 },
  { id: 7, platformId: 2, name: "Пост", multiplier: 1.0 },

  // YouTube (platformId: 3)
  { id: 8, platformId: 3, name: "Видео-обзор", multiplier: 2.0 },
  { id: 9, platformId: 3, name: "Вставка в видео", multiplier: 1.5 },
  { id: 10, platformId: 3, name: "Shorts", multiplier: 1.0 },

  // Сайт (platformId: 4)
  { id: 11, platformId: 4, name: "Баннер", multiplier: 0.8 },
  { id: 12, platformId: 4, name: "Статья", multiplier: 1.5 },
  { id: 13, platformId: 4, name: "Ссылка", multiplier: 0.6 },
];
