version: "3"
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:80"
    env_file:
      - deploy.env
    volumes:
      - ./nginx.conf:/etc/nginx/sites-enabled/default
