export enum ENUM_VOICE_AGENT_ACTIONS {
  NAVIGATE_USER = "NAVIGATE_USER",
  ADD_TO_CART = "ADD_TO_CART",
  REMOVE_FROM_CART = "REMOVE_FROM_CART",
  PIPELINE_INTENT = "PIPELINE_INTENT",

  // Pipeline actions
  NAVIGATE = "NAVIGATE",
  SET_FIELD = "SET_FIELD",
  GENERATE_TEXT = "GENERATE_TEXT",
  CONFIRM = "CONFIRM",
  PAY = "PAY",
}

export enum ENUM_PIPELINE {
  ORDER_CREATION = "ORDER_CREATION",
}

export enum ENUM_CREATE_ORDER_ACTIONS {
  CAMPAIGN_NAME = "CAMPAIGN_NAME",
  POST_TEXT = "POST_TEXT",
  SCHEDULE = "SCHEDULE",
}
