export enum pageFilter {
  order = "order",
  offer = "offer",
  platform = "platform",
  profile = "profile",
  catalog = "catalog",
  turnkey = "turnkey",
  walletTopUp = "walletTopUp",
  walletWithdraw = "walletWithdraw",
  createOrderFiles = "createOrderFiles",
  adminReviews = "adminReviews",
  adminComplaint = "adminComplaint",
  chat = "chat",
  cart = "cart",
}
