export enum paths {
  main = "/",
  mainBlogger = "/blogger",
  profile = "/profile",
  notFound = "/*",
  catalog = "/catalog",
  cart = "/cart",
  turnkey = "/turnkey",
  wallet = "/wallet",
  walletTopUp = "/wallet/topup",
  walletWithdraw = "/wallet/withdraw",
  wallethistory = "/wallet/history",
  createOrder = "/createorder",
  addChannel = "/addchannel",
  addLegal = "/addLegal",
  fullServise = "/fullServise",
  orders = "/orders",
  offers = "/offers",
  myChannels = "/channels",
  channel = "/channel/:id",
  faq = "/faq",
}
