export enum paths {
  main = "/",
  mainBlogger = "/blogger",
  profile = "/profile",
  notFound = "/*",
  catalog = "/catalog",
  platformOwner = "/platformowner",
  turnkey = "/turnkey",
  wallet = "/wallet",
  addPlatform = "/addplatform",
  addProfile = "/addprofile",
  fullServise = "/fullServise",
  orders = "/orders",
  offers = "/offers",
  platforms = "/platforms",
}
