export enum paths {
  main = "/",
  mainBlogger = "/blogger",
  profile = "/profile",
  notFound = "/*",
  catalog = "/catalog",
  cart = "/cart",
  platformOwner = "/platformowner",
  turnkey = "/turnkey",
  walletTopUp = "/wallet/topup",
  walletWithdraw = "/wallet/withdraw",
  wallethistory = "/wallet/history",
  createOrder = "/createorder",
  addPlatform = "/addplatform",
  addProfile = "/addprofile",
  fullServise = "/fullServise",
  orders = "/orders",
  offers = "/offers",
  platforms = "/platforms",
  faq = "/faq",
}
