export const enum CALENDAR {
  // disabledDays = 2,
  disabledDays = -1,
}

export const enum INTERSECTION_ELEMENTS {
  CATALOG = 10,
  ADV_ORDERS = 4,
  BLOGGER_OFFERS = 4,
  BLOGGER_CHANNELS = 4,
  BLOGGER_MODERATION_CHANNELS = 4,
  HISTORY = 5,
  CHAT = 20,
  MANAGER_ORDERS = 4,
  CHANNEL_REVIEWS = 4,
  REC_CARDS_CHANNEL = 10,
  REC_CARDS_CART = 10,
  NOTIFICATIONS = 15,
  ADMIN_CHANNELS = 5,
  ADMIN_USERS = 5,
  ADMIN_TRANSACTIONS = 5,
  ADMIN_COMPLAINTS = 1,
  ADMIN_REVIEWS = 5,
}

export const enum BREAKPOINT {
  XL = 1366,
  LG = 992,
  MD = 768,
  SM = 576,
  XS = 375,
  HEADER_NAVBAR_VISIBLE = 1400,
}
