export const enum ENUM_CALENDAR {
  // disabledDays = 2,
  disabledDays = -1,
}

export const enum INTERSECTION_ELEMENTS {
  CATALOG = 10,
  ADV_PROJECTS = 4,
  BLOGGER_OFFERS = 4,
  BLOGGER_CHANNELS = 4,
  BLOGGER_MODERATION_CHANNELS = 4,
  HISTORY = 10,
  CHAT = 20,
  DOCUMENTS = 5,
  MANAGER_PROJECTS = 4,
  CHANNEL_REVIEWS = 4,
  REC_CARDS_CHANNEL = 10,
  REC_CARDS_CART = 10,
  NOTIFICATIONS = 15,
  ADMIN_CHANNELS = 10,
  ADMIN_USERS = 10,
  ADMIN_TRANSACTIONS = 10,
  ADMIN_ACCOUNTING = 10,
  ADMIN_COMPLAINTS = 5,
  ADMIN_REVIEWS = 5,
}

export const enum BREAKPOINT {
  XL = 1366,
  LG = 992,
  MD = 768,
  SM = 576,
  XS = 375,
  HEADER_NAVBAR_VISIBLE = 1400,
}
