import { authBaseQuery } from "@entities/user";
import { createApi } from "@reduxjs/toolkit/query/react";
import {
  ADMIN_CHANNELS,
  ADMIN_COMPLAINTS,
  ADMIN_REVIEWS,
  ADV_PROJECTS,
  BALANCE,
  BLOGGER_CHANNELS,
  BLOGGER_OFFERS,
  CART,
  CART_PUB,
  CATALOG,
  CHAT,
  LEGALS,
  MANAGER_PROJECTS,
  RECOMMEND_CARDS,
  VIEWS_ADVERTISER,
  VIEWS_BLOGGER_CHANNELS,
  VIEWS_BLOGGER_OFFERS,
  VIEWS_MANAGER,
  VIEWS_TRANSACTIONS,
} from "@shared/api";

export const authApi = createApi({
  baseQuery: authBaseQuery,
  reducerPath: "authApi",
  endpoints: () => ({}),
  tagTypes: [
    CART,
    CATALOG,
    RECOMMEND_CARDS,
    BLOGGER_CHANNELS,
    CART_PUB,
    BALANCE,
    BLOGGER_OFFERS,
    ADV_PROJECTS,
    MANAGER_PROJECTS,
    LEGALS,
    CHAT,
    ADMIN_REVIEWS,
    ADMIN_COMPLAINTS,
    ADMIN_CHANNELS,
    VIEWS_BLOGGER_CHANNELS,
    VIEWS_BLOGGER_OFFERS,
    VIEWS_ADVERTISER,
    VIEWS_MANAGER,
    VIEWS_TRANSACTIONS,
  ],
});
